steps:
# --- STREAMLIT SERVICE ---
# 1. Build the Streamlit Image by targeting the specific Dockerfile stage.
- name: 'gcr.io/cloud-builders/docker'
  id: Build Streamlit
  args: ['build', '--tag', 'australia-southeast2-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/evidencesynthesis-stack-streamlit:$COMMIT_SHA', '--target', 'automated_citation_search_st_builder', '.', '-f', 'Dockerfile']


# 2. Push the built Streamlit image to Artifact Registry.
- name: 'gcr.io/cloud-builders/docker'
  id: Push Streamlit Image
  args:
    - 'push'
    - 'australia-southeast2-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/evidencesynthesis-stack-streamlit:$COMMIT_SHA'

# 3. Deploy the Streamlit Service using the pushed image.
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  id: Deploy Streamlit
  args: [
    'gcloud', 
    'run', 'deploy', 'evidencesynthesis-stack-streamlit', '--image', 'australia-southeast2-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/evidencesynthesis-stack-streamlit:$COMMIT_SHA', 
    '--region', 'australia-southeast2', 
    '--platform', 'managed', 
    '--allow-unauthenticated', 
    '--quiet', 
    '--update-secrets=semanticscholar_api_key=SEMANTICSCHOLAR_API_KEY:latest,oa_email_address=OA_EMAIL_ADDRESS:latest']

# --- R SHINY SERVICE ---
# 4. Build the R Shiny Image by targeting the specific Dockerfile stage.
- name: 'gcr.io/cloud-builders/docker'
  id: Build R Shiny
  args: ['build', '--tag', 'australia-southeast2-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/evidencesynthesis-stack-rshiny:$COMMIT_SHA', '--target', 'searchbuildR_builder', '.', '-f', 'Dockerfile']
# 5. Push the built R Shiny image to Artifact Registry.
- name: 'gcr.io/cloud-builders/docker'
  id: Push R Shiny Image
  args: ['push', 'australia-southeast2-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/evidencesynthesis-stack-rshiny:$COMMIT_SHA']
# 6. Deploy the R Shiny Service using the pushed image.

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  id: Deploy R Shiny
  args: ['gcloud', 'run', 'deploy', 'evidencesynthesis-stack-rshiny', '--image', 'australia-southeast2-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/evidencesynthesis-stack-rshiny:$COMMIT_SHA', '--region', 'australia-southeast2', '--platform', 'managed', '--allow-unauthenticated', '--quiet','--port', '6909']

options:
  logging: CLOUD_LOGGING_ONLY